1.
yum install python-pip
yum install python2-pyvmomi
pip install python2-pyvmomi

2.
# Ansible Collection  community.vmware
# It conatain the module and plugin with a lot of useful autoation to perform any task and operation in VMware

https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_info_module.html

 # Here’s how to configure Ansible for VMware:

# 1. Install pyVmomi.

pip install pyVmomi

# 2. Install the community.vmware collection.

Create a file with -- > requirements.yml
---
collections:
  - name: community.vmware

#The execution is pretty smooth via the ansible-galaxy tool:


$ ansible-galaxy install -r requirements.yml


#For Document

ansible-doc vmware_portgroup



The Ansible inventory is super simple and is limited to localhost because the Ansible controller is going to connect to the VMware infrastructure via the VMware API.

**Inventory**
localhost


# First Sample Ansible Script

**vm_info.yml**
---
- name: info vm demo
  hosts: localhost

  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: get VM info
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name }}"
      register: detailed_vm_info
    - name: print VM info
      ansible.builtin.debug:
        var: detailed_vm_info

**vars.yml**


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
vm_name: "myvm"
---
- vmware_guest_info: module to verify the successful configuration.


**Community.Vmware**
https://docs.ansible.com/ansible/latest/collections/community/vmware/index.html


https://github.com/vmware/pyvmomi

https://github.com/vmware/vsphere-automation-sdk-python

pyVmomi: VMware vSphere API Python bindings

vsphere-automation-sdk-python: VMware vSphere Automation SDK for Python

