# Gathering VMware Host Information on a Cluster

#Ansible Module vmware_host_config_info
#   community.vmware.vmware_host_config_info

#You can collect configuration and runtime information about a VMware ESXi host using the Ansible module #vmware_host_config_info. The full name is community.vmware.vmware_host_config_info, which means that it is part of the #collection of modules that interact with VMware and is community supported. The module’s purpose is to gather an ESXi #host’s advanced configuration information.

host_info_cluser.yml


---
- name: host in cluster info demo
  hosts: localhost

  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: Gather info about all ESXi Host in the given Cluster
      community.vmware.vmware_host_config_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: "{{ vcenter_validate_certs }}"
        cluster_name: "{{ cluster_name }}"
      register: cluster_info

    - name: print cluster info
      ansible.builtin.debug:
        var: cluster_info

vars.yml


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
cluster_name: "production"


