# Getting VMware Datastore Status

#Ansible Module vmware_datastore_info
#   community.vmware.vmware_datastore_info

You can collect information about a VMware datastore using the Ansible module vmware_datastore_info. The full name is community.vmware.vmware_datastore_info, which means that it is part of the collection of modules that interact with VMware and is community supported. The module’s purpose is to gather information about datastores available in a specific VMware vCenter.

datastore_info.yml


---
- name: datastore info demo
  hosts: localhost

  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: datastore info
      vmware_datastore_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter_name: "{{ vcenter_datacenter }}"
        name: "{{ vcenter_datastore }}"
      register: datastore_info
    - name: print datastore info
      ansible.builtin.debug:
        var: datastore_info

vars.yml


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
vcenter_datastore: "Datastore"


