# Getting the Status of VMware Guest Tools

#Ansible Module vmware_guest_tools_info
#   community.vmware.vmware_guest_tools_info

#You can collect information about the status of VMware guest tools using the Ansible module vmware_guest_tools_info. 
#The full name is community.vmware.vmware_guest_tools_info, which means that it is part of the collection of 
#modules that interact with VMware and is community supported. The module’s purpose is to gather information 
#about VMware guest tools installed in a VMware virtual machine.




vm_guest_tools_info.yml


---
- name: vmware guest tools info demo
  hosts: localhost

  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: guest tools info
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
      register: vmtools_info

    - name: print guest tools info
      ansible.builtin.debug:
        var: vmtools_info

vars.yml


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
vm_name: "myvm"



#Output are;--
#VMware virtual machine myvm VMware guest tools status is

VMware guest tools installed ("vm_tools_version_status": "toolsOk")

VMware guest tools running ("vm_tools_running_status": "guestToolsRunning")

VMware guest tools type OpenVM ("vm_tools_install_type": "guestToolsTypeOpenVMTools")

VMware guest tools upgrade policy manual ("vm_tools_upgrade_policy": "manual")

#VMware virtual machine myvm VMware guest tools status is

VMware guest tools NOT installed ("vm_tools_version_status": "guestToolsNotInstalled")

VMware guest tools NOT running ("vm_tools_running_status": "guestToolsNotRunning")

VMware guest tools upgrade policy manual ("vm_tools_upgrade_policy": "manual")