#   Upgrading VMware Guest Tools

#Ansible Module vmware_guest_tools_upgrade
#   community.vmware.vmware_guest_tools_upgrade

You can collect information about a VMware datastore using the Ansible module vmware_guest_tools_upgrade. The full name is community.vmware.vmware_guest_tools_upgrade, which means that it is part of the collection of modules that interact with VMware and is community supported. The module’s purpose is to smoothly upgrade the VMware guest tools installed in a VMware virtual machine.



vm_guest_tools_upgrade.yml


---
- name: vmware guest tools upgrade demo
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: VM powered-on
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name }}"
        state: powered-on

    - name: VM get UUID
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name }}"
      register: detailed_vm_info

    - name: vmware guest tools upgrade
      vmware_guest_tools_upgrade:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        uuid: "{{ detailed_vm_info.instance.hw_product_uuid }}"

    - name: guest tools info
      vmware_guest_tools_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
      register: vmtools_info

    - name: print guest tools info
      ansible.builtin.debug:
        var: vmtools_info

vars.yml


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
vm_name: "myvm"



