# Live Migration of a VMware Virtual Machine Using vMotion


#Ansible vmware_vmotion Module
#   community.vmware.vmware_vmotion

The Ansible module vmware_vmotion is used to move VMware virtual machines in your VMware infrastructure using VMware vMotion technology. The full name is community.vmware.vmware_vmotion, which means that it is part of the collection of modules that interact with VMware and is community supported. The module’s purpose is to move a virtual machine using vMotion.


vm_vmotion.yml


---
- name: vm vmotion demo
  hosts: localhost

  gather_facts: false
  vars:
    destination_host: "host2.vmware.example.com"
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: VM vmotion
      vmware_vmotion:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        vm_name: "{{ vm_name }}"
        destination_host: "{{ destination_host }}"
      register: vm_info

    - name: VM running host
      ansible.builtin.debug:
        var: vm_info.running_host

vars.yml


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
vm_name: "myvm"


