# Changing the Boot Device Order of a VMware Virtual Machine

#Ansible Module vmware_guest_boot_manager
#   community.vmware.vmware_guest_boot_manager

You can collect information about the VMware guest tools status using the Ansible module vmware_guest_boot_manager. The full name is community.vmware.vmware_guest_boot_manager, which means that it is part of the collection of modules that interact with VMware and is community supported. The module’s purpose is to manage boot options for the given virtual machine in a VMware virtual machine.


vm_change_boot.yml


---
- name: vm change book demo
  hosts: localhost

  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: VM change boot order
      vmware_guest_boot_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name }}"
        enter_bios_setup: true
        boot_order:
          - cdrom
          - disk
          - ethernet

vars.yml


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
vm_name: "myvm"



