# Creating a VMware Virtual Machine

# Ansible vmware_guest Module
#    community.vmware.vmware_guest

#The Ansible module vmware_guest is used to interact with your VMware infrastructure and create or manage VMware 
#  virtual machines. The full name is community.vmware.vmware_guest, which means that it is part of the collection 
#   of modules that interact with VMware and is community supported. The module vmware_guest has a very long list 
#   of parameters to customize all your needs to create a VMware vSphere virtual machine. The resource allocation 
#   list is especially extended to cover the more possible use cases. I suggest you begin with a minimum solution 
#   and then improve it little by little until you reach your expected outcome. It may be difficult to troubleshoot
#  several lines of code and options at a time. Please refer to the manual for the full list.

**create_vm.yml**


---
- name: create vm demo
  hosts: localhost

  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: create VM folder
      vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter_name: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: vm
        state: present
    - name: create VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        folder: "{{ vcenter_destination_folder }}"
        state: "{{ vm_state }}"
        guest_id: "{{ vm_guestid }}"
        cluster: "{{ vcenter_cluster }}"
        disk:
          - size_gb: "{{ vm_disk_gb }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
        hardware:
          memory_mb: "{{ vm_hw_ram_mb }}"
          num_cpus: "{{ vm_hw_cpu_n }}"
          scsi: "{{ vm_hw_scsi }}"
        networks:
          - name: "{{ vm_net_name }}"
            device_name: "{{ vm_net_type }}"

**vars.yml**


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
vcenter_cluster: "Development"
vm_name: "myvm"
vm_guestid: "centos64Guest"
vm_disk_gb: 10
vm_disk_type: "thin"
vm_disk_datastore: "Datastore-1"
vm_hw_ram_mb: 1024
vm_hw_cpu_n: 1
vm_hw_scsi: "paravirtual"
vm_net_name: "VM Network"
vm_net_type: "vmxnet3"
vcenter_destination_folder: "myvm"
vm_state: "poweroff"