# Deploying a VMware Virtual Machine from a Template

# Ansible Module vmware_guest
#    community.vmware.vmware_guest

https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html

vm_deploy_template.yml

---
- name: deploy vm from template demo
  hosts: localhost

  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
      - name: create VM folder
        vcenter_folder:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: "{{ vcenter_validate_certs }}"
          datacenter_name: "{{ vcenter_datacenter }}"
          folder_name: "{{ vcenter_destination_folder }}"
          folder_type: vm
          state: present
      - name: deploy VM from template
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: "{{ vcenter_validate_certs }}"
          datacenter: "{{ vcenter_datacenter }}"
          cluster: "{{ vcenter_cluster }}"
          name: "{{ vm_name }}"
          folder: "{{ vcenter_destination_folder }}"
          template: "{{ vm_template }}"



vars.yml


---
vcenter_hostname: "vmware.example.com"
vcenter_datacenter: "vmwaredatacenter"
vcenter_validate_certs: false
vcenter_username: "username@vsphere.local"
vcenter_password: "MySecretPassword123"
vcenter_cluster: "Development"
vm_name: "myvm"
vcenter_destination_folder: "myvm"
vm_state: "poweroff"
vm_template: "mytemplate"


