- name: install and start srver
  yum:
    name: 
      - "{{ ansible_local.custom.packages.ftp_root }}"
      - "{{ ansible_local.custom.packages.web_root }}"
    state: latest

- name: start db
  service: 
    name: "{{ ansible_local.custom.services.ftp_service }}"
    state: started
    enabled: true

- name: start webb
  service:
    name: "{{ ansible_local.custom.packages.web_service }}"      
    state: started
    enabled: true 