- name: install remote fact
  hosts: all
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: create remote directory
      file:
        state: directory
        resurse: yes
        path: "{{ remote_dir }}"

    - name: install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
