- name: yum module
  hosts: all
  become: true
  tasks:
    - name: update ngnix
      yum:
        name: ngnix
        state: latest
        update_cache: true

# Rollimg update Redhat by yum module
# ansible-playbook -i update.yml


