- name: nested loop
  hosts: all
  vars:
    myusers:
      - rohit
      - raj
    mygroups:
      - student
      - sales
  tasks:
  - name: create group
    group:
      name: "{{ item }}"
      state: present
    with_items: "{{ mygroups }}"

  - name: create user and group assign
    user:
      name: "{{ item[0] }}"
      state: present 
      groups: "{{ item[1] }}"
    with_nested:
      - "{{ myusers }}"
      - "{{ mygroups }}"     
