- name: service
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: install httpd
    yum: 
      name: httpd
      state: latest

  - name: insatll firewall
    yum: 
      name: firewalld
      state: latest

  - name: httpd enable and running
    service: 
      name: httpd
      enabled: true
      state: started

  - name: firewall enable
    service: 
      name: firewalld
      enabled: true
      state: started

  - name: allow
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify:
      - restart firewallds


  