- name: deploy
  hosts: all
  include_vars: vars/{{ ansible_os_family }}.yml
  tasks:
  - name: install and update latest packages
    packages:
      name:
        - "{{ web_package }}"
        - "{{ ftp_package }}"
        - "{{ db_package }}"
        - "{{ firewalld_package }}"
      state: latest
      notify:
        - success

  - name: start and enable {{ firewall_service }}
    service:
      name: "{{ firewall_service }}"
      enabled: true
      state: started

  - name: start and enable {{ web_service }} 
    service:
      name: "{{ web_service }}"
      enable: true
      state: started

  - include_tasks: ubuntu.yml
    when: ansible_os_family == 'Ubuntu'   

  - include_tasks: redhat.yml
    when: ansible_os_family == 'Redhat'   
