#$ echo 'ubuntu_version: "Ubuntu 18.04.5 LTS"' >> version.yml
#$ echo 'centos_version: "8.2"' >> version.yml
#$ cat version.yml
#ubuntu_version: "Ubuntu 18.04.5 LTS"
#centos_version: "8.2"

---
- name: Upgrade Systems
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: read the variables file
      include_vars:
        file: version.yml
    - name: Upgrade Older Systems
      package:
        name: "*"
        state: latest
      when: >
        (ansible_distribution == "CentOS" and ansible_distribution_version != centos_version) or
        (ansible_distribution == "Ubuntu" and ansible_lsb.description != ubuntu_version)
...