#Install the Database Role

#1.Create Variable File
#------------------------
#$ vim $HOME/ansible/apache ; mkdir vars
#$ vim vars/main.yml
---
mysql_root_password: Password1
mysql_root_password_update: true
mysql_enabled_on_startup: true
mysql_users:
  - name: bob
    host: "%"
    password: Password1
    priv: "*.*:ALL"

#2.Installing the MySQL Role and Implementing a Database Server
#---------------------------------------------------------------

#ansible-galaxy install geerlingguy.mysql
#$ vim  $HOME/ansible/apache/full_apache.yml
---
- name: Manage Apache Deployment
  hosts: all
  become: true
  gather_facts: true
  vars:
    - service_name: http
    - php_enable_webserver: true
  vars_files:
    - vars/main.yml
  roles:
    - apache
    - firewall
    - standard_web
    - geerlingguy.php
    - geerlingguy.mysql
  tasks:
    - name: add php page
      copy:
        dest: /var/www/html/test.php
        content: "<?php phpinfo(); ?>"
    - name: Install mysql-php
      package:
        name: "{{ php_mysql }}"
      notify: restart webserver
    - name: Add Apache PHP and Enable on Ubuntu
      block:
        - name: Install Apache PHP Module
          apt:
            name: libapache2-mod-php
            state: present
          notify: restart webserver
        - name: Enable PHP Module
          apache2_module:
            state: present
            name: php7.2
          notify: restart web server
      when: ansible_distribution == "Ubuntu"



#$ vim full_apache.yml
---
# New Play 1
- name: Enable MySQL Port
  hosts: all
  gather_facts: true
  become: true
  vars:
    - service_name: mysql
  roles:
    - firewall
# Existing Play is now Play 2
- name: Manage Apache Deployment


