- name: create User and change password
  hosts: all
  tasks: 
  - name: create user
    user:
        name: "{{ item }}"
        state: present
    with_items:
        - user1
        - user2
    tags: users
  - name: Password for user
    shell:
        echo "user1:qwerty" | /usr/sbin/chpasswd

  - name: Password for user2
    shell:
        echo "user2:qwerty" | /usr/sbin/chpasswd

  - name: Change password first login
    command:
        chage -d 0 user1

    