- name: copy file from src to dest server
  hosts: all
  tasks:
  - name: copy 
    copy:
        src: /root/nrpe.cfg
        dest: /usr/local/nagios/etc/
  - name: restart nrpe 
    systemd:
      name: nrpe
      state: restarted

