- name: Create User and change password and Add in wheel group
  hosts: all
  tasks: 
  - name: create user
    user:
        name: "{{ item }}"
        state: present
    with_items:
        - user1
        - user2
        - user3
    tags: users
  - name: Password for user
    shell:
        echo "user1:qwerty" | /usr/sbin/chpasswd

  - name: Password for user2
    shell:
        echo "user2:qwerty" | /usr/sbin/chpasswd

  - name: Change password first login
    command:
        chage -d 0 user3
  - name: Add in wheel group
    user:
      name: "{{ item }}"
      groups: wheel
    with_items:
      - user1
      - user2
      - user3
    