- name: delete the content from file
  hosts: testip
  tasks:
  - name: delete the content
    blockinfile:
        path: /home/jai/file
        marker: "{{ item }}"
        backup: yes
    with_items:
        - 2
        - 4
        - 7

