- name: Delete User with Home Directory
  hosts: all
  tasks: 
  - name: create user
    user:
        name: "{{ item }}"
        state: absent
        remove: yes                 
        force: yes
    with_items:
        - user1
        - user2
        - user3
    tags: users
  

  #remove =  remove the home directory
  #force = remove the file in the directory
  