---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'Debain'

- name: Install Docker
  packages: 
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enable at boot
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handler are notified now to avoid firewall
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users
    

