- name: handler
  hosts: all
  tasks:
  - name: install httpd
    packages:
      name: httpd
      state: present
  - name: start
    service:
      name: httpd
      state: started
  - name: index file
    copy:
      src: /tmp/index.html
      dest: "/var/www/html/index.html"
    notify:
      - restart_web
  handler:
    - name: restart_web
      service:
        name: httpd
        state: restarted
